name: SecretlyFollowHerWeibo
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: jianxinli <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  async: ^2.0.0
  logging: '>0.0.1 <1.0.0'
  intl: '>0.9.0 <1.0.0'
  mime: '>0.9.0 <1.0.0'
  path: '>0.9.0 <2.0.0'
  dart2_constant: ^1.0.0
dev_dependencies:
  test: ^1.0.0
