name: SecretlyFollowHerWeibo
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: jianxinli <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  mailer: ^2.1.2

dev_dependencies:
  test: ^1.0.0
